language: c
compiler:
 - clang
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
  - sudo add-apt-repository --yes ppa:ben-collins/libjwt && sudo apt-get update && sudo apt-get install --yes libjwt-dev
script: bash -ex .travis-opam.sh
env:
  global:
    - TESTS=true
  matrix:
    - OCAML_VERSION=4.06 PACKAGE="jwt_c" PINS="jwt_c:."
